(()=>{"use strict";
const c=document.getElementById("gameCanvas"),x=c.getContext("2d",{alpha:false}),$=id=>document.getElementById(id);
let W=960,H=540,dpr=1,state="menu",raf=0,last=0,score=0,coins=0,distance=0,elapsed=0,speed=260,spawn=0,coinSpawn=0;
let best=Number(localStorage.getItem("gamezoneSkyRushBest")||0),obs=[],items=[],parts=[],clouds=[],keys=new Set(),touch=false;
const p={x:130,y:270,vy:0,rot:0,shield:0};
function resize(){let r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=Math.max(320,r.width);H=Math.max(260,r.height);c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener("resize",resize);resize();
function hud(){$("score").textContent=Math.floor(score);$("coins").textContent=coins;$("shield").textContent=p.shield>0?Math.ceil(p.shield)+"s":"—";$("bestScore").textContent=best}
function reset(){score=coins=distance=elapsed=0;speed=260;spawn=.8;coinSpawn=.6;obs=[];items=[];parts=[];clouds=[];p.x=W*.16;p.y=H*.5;p.vy=0;p.rot=0;p.shield=0;for(let i=0;i<7;i++)clouds.push({x:Math.random()*W,y:40+Math.random()*H*.65,s:.5+Math.random()*1.2,a:.05+Math.random()*.08});hud()}
function start(){reset();state="play";$("startScreen").classList.add("hidden");$("gameOverScreen").classList.add("hidden");$("pauseScreen").classList.add("hidden");last=performance.now();raf=requestAnimationFrame(loop)}
function over(){state="over";let f=Math.floor(score),old=best;if(f>best){best=f;localStorage.setItem("gamezoneSkyRushBest",best)}$("finalScore").textContent=f;$("finalCoins").textContent=coins;$("finalDistance").textContent=Math.floor(distance)+"m";$("finalBest").textContent=best;$("newBest").classList.toggle("hidden",f<=old);$("gameOverScreen").classList.remove("hidden");burst(p.x,p.y,22,"#ffb34a");hud()}
function pause(){if(state==="play"){state="paused";$("pauseScreen").classList.remove("hidden")}}function resume(){if(state==="paused"){state="play";$("pauseScreen").classList.add("hidden");last=performance.now();raf=requestAnimationFrame(loop)}}
function addGate(){let gap=Math.max(135,195-elapsed*2.2),cy=90+Math.random()*(H-180),w=44+Math.random()*26;obs.push({x:W+30,w,top:Math.max(28,cy-gap/2),bottom:Math.min(H-28,cy+gap/2),passed:false})}
function addItem(){items.push({x:W+20,y:65+Math.random()*(H-130),r:9,spin:Math.random()*6.28,shield:Math.random()<.09})}
function burst(a,b,n,col){for(let i=0;i<n;i++)parts.push({x:a,y:b,vx:(Math.random()-.5)*250,vy:(Math.random()-.5)*250,life:.35+Math.random()*.5,col})}
function dir(){if(touch||keys.has("ArrowUp")||keys.has("w")||keys.has("W"))return-1;if(keys.has("ArrowDown")||keys.has("s")||keys.has("S"))return 1;return 0}
function hit(a,b,w,h,A,B,W2,H2){return a<A+W2&&a+w>A&&b<B+H2&&b+h>B}
function update(dt){elapsed+=dt;speed=260+Math.min(240,elapsed*7);score+=dt*(14+elapsed*.6);distance+=dt*speed/9;spawn-=dt;coinSpawn-=dt;if(spawn<=0){addGate();spawn=Math.max(.7,1.35-elapsed*.012)*(.85+Math.random()*.3)}if(coinSpawn<=0){addItem();coinSpawn=.5+Math.random()*.8}
let d=dir();p.vy+=(d<0?-760:d>0?620:180)*dt;p.vy*=Math.pow(.09,dt);p.y+=p.vy*dt;p.y=Math.max(24,Math.min(H-24,p.y));p.rot=Math.max(-.42,Math.min(.42,p.vy/650));
obs.forEach(o=>o.x-=speed*dt);items.forEach(i=>{i.x-=speed*dt;i.spin+=dt*6});obs=obs.filter(o=>o.x>-70);items=items.filter(i=>i.x>-50);
for(const o of obs){if(!o.passed&&o.x+o.w<p.x){o.passed=true;score+=35}if(hit(p.x-20,p.y-11,40,22,o.x,0,o.w,o.top)||hit(p.x-20,p.y-11,40,22,o.x,o.bottom,o.w,H-o.bottom)){if(p.shield>0){p.shield=0;o.x=-200;burst(p.x,p.y,15,"#6de1ff")}else{over();return}}}
for(let i=items.length-1;i>=0;i--){let q=items[i];if(Math.hypot(p.x-q.x,p.y-q.y)<26){if(q.shield){p.shield=8;score+=80;burst(q.x,q.y,12,"#6de1ff")}else{coins++;score+=60;burst(q.x,q.y,8,"#ffd34d")}items.splice(i,1)}}if(p.shield>0)p.shield-=dt;
parts.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=160*dt;q.life-=dt});parts=parts.filter(q=>q.life>0);hud()}
function draw(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,"#092846");g.addColorStop(.55,"#147d9f");g.addColorStop(1,"#092e48");x.fillStyle=g;x.fillRect(0,0,W,H);let s=x.createRadialGradient(W*.78,H*.2,3,W*.78,H*.2,90);s.addColorStop(0,"rgba(255,244,180,.5)");s.addColorStop(1,"rgba(255,244,180,0)");x.fillStyle=s;x.fillRect(0,0,W,H);
clouds.forEach(q=>{q.x-=speed*.012*q.s;if(q.x<-180)q.x=W+100;x.fillStyle=`rgba(255,255,255,${q.a})`;cloud(q.x,q.y,80*q.s)});x.fillStyle="rgba(8,52,67,.45)";x.beginPath();x.moveTo(0,H);x.lineTo(0,H*.82);for(let z=0;z<=W;z+=90)x.lineTo(z,H*.72-Math.sin(z*.012)*35);x.lineTo(W,H);x.fill();
obs.forEach(o=>{gate(o.x,0,o.w,o.top);gate(o.x,o.bottom,o.w,H-o.bottom)});items.forEach(q=>{x.save();x.translate(q.x,q.y);x.rotate(q.spin);if(q.shield){x.strokeStyle="#78e4ff";x.lineWidth=4;x.beginPath();x.arc(0,0,13,0,Math.PI*2);x.stroke();x.fillStyle="#bff5ff";x.font="bold 12px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText("S",0,1)}else{x.fillStyle="#ffd34d";x.beginPath();x.arc(0,0,9,0,Math.PI*2);x.fill();x.strokeStyle="#fff0a1";x.stroke();x.fillStyle="#98650c";x.font="bold 9px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText("G",0,1)}x.restore()});plane();parts.forEach(q=>{x.globalAlpha=Math.max(0,q.life);x.fillStyle=q.col;x.beginPath();x.arc(q.x,q.y,2.5,0,Math.PI*2);x.fill();x.globalAlpha=1})}
function cloud(a,b,s){x.beginPath();x.arc(a,b,s*.32,0,6.28);x.arc(a+s*.25,b-s*.16,s*.4,0,6.28);x.arc(a+s*.57,b,s*.3,0,6.28);x.fill()}
function gate(a,b,w,h){if(h<=0)return;let g=x.createLinearGradient(a,0,a+w,0);g.addColorStop(0,"#142235");g.addColorStop(.5,"#294461");g.addColorStop(1,"#0d1827");x.fillStyle=g;x.fillRect(a,b,w,h);x.fillStyle="#63c6ff";x.fillRect(a-4,b+h-5,w+8,5);x.fillStyle="rgba(100,205,255,.12)";x.fillRect(a+7,b,4,h)}
function plane(){x.save();x.translate(p.x,p.y);x.rotate(p.rot);if(p.shield>0){x.strokeStyle="rgba(95,220,255,.75)";x.lineWidth=4;x.beginPath();x.arc(0,0,35+Math.sin(elapsed*8)*3,0,6.28);x.stroke()}x.fillStyle="#ffb43b";x.beginPath();x.moveTo(-27,0);x.lineTo(-45,-6-Math.random()*5);x.lineTo(-31,5);x.closePath();x.fill();x.fillStyle="#e9f3ff";x.beginPath();x.moveTo(29,0);x.lineTo(3,-12);x.lineTo(-20,-9);x.lineTo(-10,0);x.lineTo(-20,9);x.lineTo(3,12);x.closePath();x.fill();x.fillStyle="#55b9ff";x.beginPath();x.moveTo(5,0);x.lineTo(-5,-19);x.lineTo(-12,-18);x.lineTo(-8,-2);x.closePath();x.fill();x.fillStyle="#234a73";x.beginPath();x.ellipse(9,-2,7,4,0,0,6.28);x.fill();x.restore()}
function loop(t){if(state!=="play")return;let dt=Math.min(.035,(t-last)/1000);last=t;update(dt);draw();if(state==="play")raf=requestAnimationFrame(loop)}
$("startBtn").onclick=start;$("restartBtn").onclick=start;$("pauseBtn").onclick=pause;$("resumeBtn").onclick=resume;
addEventListener("keydown",e=>{keys.add(e.key);if(["ArrowUp","ArrowDown"," "].includes(e.key))e.preventDefault();if(e.key==="Escape"&&state==="play")pause();else if(e.key==="Escape"&&state==="paused")resume()});addEventListener("keyup",e=>keys.delete(e.key));
c.addEventListener("pointerdown",e=>{touch=true;c.setPointerCapture?.(e.pointerId)});c.addEventListener("pointerup",()=>touch=false);c.addEventListener("pointercancel",()=>touch=false);
reset();draw();
})();